### ISSUE TITLE
Let's start? :)

### ISSUE THREAD

**Issue by GreatWizard** [pylaligand/destiny2-slack-bot#1]
Do you need any help?
Do you want to try some new shiny bot framework in another language than dart?
I would like to help you if you are motivated :) I have preferences for nodejs framework.

**Comment by pylaligand** [comment]
Hey, thanks for the interest! I've been playing the game hence the lack of progress here, but stay tuned for updates this week-end.

I'm very happy with Dart and will stick with it for this new bot. I'll happily take PRs though.

**Comment by pylaligand** [comment]
FYI I've started adding stuff.

**Comment by GreatWizard** [comment]
Oh it's in dart

I wonder why you use this language for a slack bot ? Is there a good "framework"/librairy for this purpose ?

**Comment by pylaligand** [comment]
Well, why not? I built a simple framework for it and it's served me well.
